### PR TITLE
Add CFF file

### PR DESCRIPTION
**Pull request by BobBorges**
Please fill in your orcids or paste them in the comments. Missing GH aliases for some authors -- do we know about Pelle, Johan, or Anders?

### CODE REVIEW

**Comment by BobBorges** [comment]
@MansMeg @ninpnin @fredrik1984 @Lottabrorsson

**Comment by fredrik1984** [comment]
Pelle: https://orcid.org/0000-0001-5122-1549
Johan: https://orcid.org/0000-0002-1167-046X

Don't think Anders has ORCID

**Comment by BobBorges** [comment]
do they have github accounts?

**Comment by fredrik1984** [comment]
> do they have github accounts?

Johan should have

My ORCID: https://orcid.org/0000-0001-8820-1082

**Comment by MansMeg** [comment]
My orcid:
0000-0002-0296-2719

**Comment by Lottabrorsson** [comment]
> @MansMeg @ninpnin @fredrik1984 @Lottabrorsson

@BobBorges should I create one?

**Comment by BobBorges** [comment]
I think it's not necessary just for this, but if you want, just let me know and I'll add it to the file.

**Pull request merged**
