### PR TITLE
feat: protocols 202223

### PR DESCRIPTION
**Pull request by ninpnin**

### CODE REVIEW

**Comment by BobBorges** [comment]
Any thoughts on this? @ninpnin @MansMeg? v1. is released so we don't have to be afraid of adding new data :D

**Comment by ninpnin** [comment]
Tests pass. Maybe it would be good to check that none of the files are empty. Otherwise LGTM

**Comment by BobBorges** [comment]
Pushed a test for that. the new files are fine, but 1 and 2 of 199192 are empty. I guess we should fix those files before adding the test to the workflow. Will merge the 202223 records after this workflow run finishes.

**Comment by MansMeg** [comment]
Its actually good practice to do the opposite. Ie in the branch first add the test then fix it. Great work!

**Comment by BobBorges** [comment]
I didn't want to delay adding 202223 because of an issue in 199091, but I can do it either way. Interesting that the mp test fails now though... in this particular case, it's wikidata that's wrong...

**Comment by MansMeg** [comment]
Ok. Fair enough. Then I would say first add the new data, then add the tests then fix the tests.

**Comment by ninpnin** [comment]
@BobBorges I think we should use protocol_iterators without the start and end arguments. That way, we will get all of them even if the years change.

**Comment by BobBorges** [comment]
> @BobBorges I think we should use protocol_iterators without the start and end arguments. That way, we will get all of them even if the years change.

fair https://github.com/swerik-project/riksdagen-records/pull/7/commits/113c0aeb4173a3d5fe7e72523ccc43ab9838dc7c

**Comment by BobBorges** [comment]
@ninpnin @MansMeg tests will pass. Do we want any additional quality control for new protocols?

**Comment by MansMeg** [comment]
No. When adding stuff it does not make sense to sample I think. Feel free to add if you and väinö are happy.

**Comment by BobBorges** [comment]
I'm happy. @ninpnin, are you happy?

**Comment by MansMeg** [comment]
Ping @ninpnin

**Comment by ninpnin** [comment]
lgtm

**Pull request merged**
